CREATE DATABASE CoursePlanner;

USE CoursePlanner;

CREATE TABLE Course
(
	cID CHAR(15) NOT NULL,
	cName CHAR(50) NOT NULL,
	cOffered CHAR(10) NOT NULL,
	cCredits INT NOT NULL,
	CONSTRAINT coursePK PRIMARY KEY (cID)
);

CREATE TABLE Prerequisites
(
	CourseID CHAR(15) NOT NULL,
	PreReqID CHAR(15) NOT NULL,
	Arb INT NOT NULL, /*To be dropped after population */
	CONSTRAINT PreReqPK PRIMARY KEY (CourseID, PreReqID),
	CONSTRAINT CourseFK FOREIGN KEY (CourseID) REFERENCES Course(cID),
	CONSTRAINT PreReqFK FOREIGN KEY (PreReqID) REFERENCES Course(cID)
);

CREATE TABLE MajorMinor
(
	mName CHAR(50) NOT NULL,
	Major INT,
	mID INT NOT NULL,
	CONSTRAINT MajorMinorPK PRIMARY KEY (mID)
);

CREATE TABLE Required
(

	CourseID CHAR(10) NOT NULL,
	MajorID INT NOT NULL,
	CONSTRAINT ReqPK PRIMARY KEY (MajorID, CourseID),
	CONSTRAINT MajorFK FOREIGN KEY (MajorID) REFERENCES MajorMinor(mID),
	CONSTRAINT CourseMFK FOREIGN KEY (CourseID) REFERENCES Course(cID)
);


CREATE TABLE Buckets
(
	MajorID INT NOT NULL,
	BucketNumber INT NOT NULL,
	RequiredAmt INT NOT NULL,
	CONSTRAINT BuckPK PRIMARY KEY (BucketNumber, MajorID),
	CONSTRAINT MajorBFK FOREIGN KEY (MajorID) REFERENCES MajorMinor(mID)
);

CREATE TABLE Contains
(

	CourseID CHAR(15) NOT NULL,
	MajorID INT NOT NULL,
	bNo INT NOT NULL,
	CONSTRAINT ContPK PRIMARY KEY (MajorID, CourseID, bNo),
	CONSTRAINT CourseCFK FOREIGN KEY (CourseID) REFERENCES Course(cID),
	CONSTRAINT MajorCFK FOREIGN KEY (MajorID) REFERENCES MajorMinor(mID),
	CONSTRAINT bNoFK FOREIGN KEY (bNo) REFERENCES Buckets(BucketNumber)
);
